INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (NULL,"Skeleton","Description",206);
  INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (1,"Axial","Description",80);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (2,"Skull","Description",28);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber,Synonymous) VALUES (3,"Cranium","Description",8,"Braincase");
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber,Synonymous) VALUES (4,"Skullcap","Description",6,"Calvaria");
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (3,"Facial Skeleton","Description",14);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (3,"Auditory Ossicles","Description",6);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (2,"Laryngeal Skeleton","Description",1);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description,Synonymous,BoneNumber) VALUES (2,"Torso","Description","Chest",51);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,Synonymous,BoneNumber) VALUES (9,"Rib Cage","Description","Thoracic Cage",24);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,Synonymous,BoneNumber) VALUES (10,"Vertebrosternal Ribs","Description","True Ribs",24);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,Synonymous,BoneNumber) VALUES (11,"Right Vertebrosternal Ribs","Description","Right True Ribs",12);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,Synonymous,BoneNumber) VALUES (11,"Left Vertebrosternal Ribs","Description","Left True Ribs",12);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (10,"False Ribs","Description",10);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,Synonymous,BoneNumber) VALUES (14,"Right False Ribs","Description","Right True Ribs",13);
            INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (15,"Right Vertebrochondal Rib","Description",3);
            INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (15,"Right Floating  Rib","Description",2);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,Synonymous,BoneNumber) VALUES (14,"Left False Ribs","Description","Left True Ribs",13);
            INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (18,"Left Vertebrochondal Rib","Description",3);
            INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (18,"Left Floating Rib","Description",2);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (9,"Vertebral Column","Description",26);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (21,"Cervical Spine","Description",7);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (21,"Lumbar Spine","Description",5);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (21,"Thoracic Spine","Description",12);
  INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (1,"Appendicular","Description",126);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber,Synonymous) VALUES (25,"Shoulder Girdle","Description",4,"Pectoral Girdle");
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber,Synonymous) VALUES (26,"Left Shoulder Girdle","Description",2,"Left Pectoral Girdle");
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber,Synonymous) VALUES (26,"Right Shoulder Girdle","Description",2,"Right Pectoral Girdle");
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (25,"Pelvic Girdle","Description",2);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (25,"Lower Limb","Description",60);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (30,"Left Lower Limb","Description",30);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (31,"Left Leg","Description",2);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (31,"Left Foot","Description",26);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (33,"Left Tarsus","Description",7);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (33,"Left Metatarsus","Description",5);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (33,"Left Foot Phalanges","Description",14);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (30,"Right Lower Limb","Description",30);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (37,"Right Leg","Description",2);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (37,"Right Foot","Description",26);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (39,"Right Tarsus","Description",7);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (39,"Right Metatarsus","Description",5);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (39,"Right Foot Phalanges","Description",14);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (25,"Upper Limb","Description",60);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (43,"Left Upper Limb","Description",30);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (44,"Left Forearm","Description",2);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (44,"Left Hand","Description",27);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (46,"Left Carpus","Description",8);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (46,"Left Metacarpus","Description",5);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (46,"Left Hand Phalanges","Description",15);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (43,"Right Upper Limb","Description",30);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (50,"Right Forearm","Description",2);
        INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (50,"Right Hand","Description",27);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (52,"Right Carpus","Description",8);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (52,"Right Metacarpus","Description",5);
          INSERT INTO BoneSet(BoneSet_idParent,Category,Description,BoneNumber) VALUES (52,"Right Hand Phalanges","Description",15);
INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (NULL,"Teeth","Description", 32);
  INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (56,"Upper Arch","Description", 16);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (57,"Upper Molars","Description", 6);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (NULL,"Upper Right Molars","Description", 3);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (NULL,"Upper Left Molars","Description", 3);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (57,"Upper Premolars","Description", 4);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (61,"Upper Right Premolars","Description", 2);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (61,"Upper Left Premolars","Description", 2);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (57,"Upper Canines","Description", 2);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (57,"Upper Lateral Incisors","Description", 2);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (57,"Upper Central Incisors","Description", 2);
  INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (56,"Lower Arch","Description", 16);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (67,"Lower Molars","Description", 6);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (68,"Lower Right Molars","Description", 3);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (68,"Lower Left Molars","Description", 3);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (67,"Lower Premolars","Description", 4);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (71,"Lower Right Premolars","Description", 2);
      INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (71,"Lower Left Premolars","Description", 2);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (67,"Lower Canines","Description", 2);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (67,"Lower Lateral Incisors","Description", 2);
    INSERT INTO BoneSet(BoneSet_idParent,Category,Description) VALUES (67,"Lower Central Incisors","Description", 2);